### ISSUE TITLE
Post Removal Request - UW Homework Solutions

### ISSUE THREAD

**Issue by jsanders89** [spascua/my-java#1]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington. Some of the posts in this repository contain solution code to an assignment based on our own Personality Test homework assignment, specifically:

https://github.com/spascua/my-java/blob/master/exercises/PersonalityTest.java
https://github.com/spascua/my-java/blob/master/exercises/PersonalityTest1.java

These posts' solution codes are indexed by Google, enabling current students to easily find them and cheat on their assignments.

Would you please remove these posts or make them private in order to help us enforce our academic policy?

By removing them, you would be removing tools that our students could use in academic misconduct.

Thank you,
Jonathan Sanders
Intro Support, Computer Science & Engineering
University of Washington
jsanders@cs.washington.edu

More info on our course: http://courses.cs.washington.edu/courses/cse142/15su/

**Comment by spascua** [comment]
Hi Jonathan,

Sorry about that I removed the files, I will keep them locally on my PC
from now on

-Stuart

**Comment by jsanders89** [comment]
Hey Stuart,

Thank you for removing those posts!  

Have a great week,
Jonathan
